# Generated by Django 4.1.7 on 2023-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
        ),
    ]
