# Generated by Django 4.1.7 on 2023-02-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
    ]
