# Generated by Django 4.1.7 on 2023-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockrooms', '0003_remove_store_id_alter_store_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('sap_code', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='Código SAP')),
                ('sup_code', models.CharField(max_length=20, unique=True, verbose_name='Código fabricante')),
                ('description', models.CharField(max_length=120, verbose_name='Descripción repuesto')),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Código SAP'),
        ),
    ]
