# Generated by Django 4.1.7 on 2023-02-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockrooms', '0004_part_alter_store_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Cantidad')),
                ('min', models.IntegerField(verbose_name='Minimo')),
                ('order', models.IntegerField(verbose_name='Reorden')),
                ('max', models.IntegerField(verbose_name='Maximo')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockrooms.part')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockrooms.store')),
            ],
        ),
    ]
