# Generated by Django 4.1.7 on 2023-02-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockrooms', '0005_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockrooms.part', unique=True),
        ),
    ]
