# Generated by Django 4.1.7 on 2023-02-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockrooms', '0017_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('part', 'store'), name='unique_part'),
        ),
    ]
