# Generated by Django 4.1.7 on 2023-02-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockrooms', '0018_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['store', 'part']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['sap_code']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['code']},
        ),
    ]
